name: portfolio
services:
- name: web
  dockerfile_path: Dockerfile
  source_dir: /
  environment_slug: node-js
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: HOST
    value: 0.0.0.0
  - key: PORT
    value: "8080"