#
# Digital Ocean App Platform Deployment Configuration - FIXED VERSION
# Simplified configuration focusing on the main application
#
name: portfolio-optimized
region: nyc1

# Environment variables
envs:
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SHARP_CACHE_SIZE
    value: "100"
  - key: SHARP_CONCURRENCY
    value: "2"
  # Monitoring and feature flags
  - key: ENABLE_MONITORING
    value: "true"
  - key: ENABLE_PROMETHEUS_METRICS
    value: "true"
  - key: HEALTH_CHECK_TIMEOUT
    value: "30000"
  - key: STARTUP_TIMEOUT
    value: "120000"
  - key: GRACEFUL_SHUTDOWN_TIMEOUT
    value: "15000"
  # Feature flags for gradual rollout
  - key: FEATURE_IMAGE_OPTIMIZATION_V2
    value: "true"
  - key: FEATURE_ENHANCED_CACHING
    value: "true"
  - key: FEATURE_PERFORMANCE_MONITORING
    value: "true"

# Main portfolio application with image optimization built-in
services:
  # Primary web application with integrated image processing
  - name: portfolio-web
    source_dir: /
    github:
      repo: SpacePlushy/portfolio
      branch: build-fixes
      deploy_on_push: true
    dockerfile_path: Dockerfile
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-s  # Increased from basic-xxs for Sharp compatibility
    
    http_port: 8080
    
    health_check:
      http_path: /api/readiness  # Use readiness for faster startup
      initial_delay_seconds: 30  # Reduced with new lifecycle management
      period_seconds: 15         # More frequent checks
      timeout_seconds: 10        # Reasonable timeout
      success_threshold: 1       # Single success needed
      failure_threshold: 3       # Quick failure detection
    
    # Liveness probe for ongoing health
    liveness_check:
      http_path: /api/health     # Comprehensive health check
      initial_delay_seconds: 60  # Allow startup time
      period_seconds: 30         # Check every 30 seconds
      timeout_seconds: 15        # Longer timeout for full check
      success_threshold: 1
      failure_threshold: 3
    
    routes:
      - path: /
      # Monitoring and health check routes
      - path: /api/health
      - path: /api/readiness
      - path: /api/monitoring
      - path: /metrics
      - path: /health-status
      - path: /monitoring
    
    envs:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8080"
      - key: REDIS_URL
        value: "${redis-cache.PRIVATE_URL}"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1536"
      # Application lifecycle settings
      - key: ENABLE_GRACEFUL_SHUTDOWN
        value: "true"
      - key: SHUTDOWN_TIMEOUT_MS
        value: "15000"
      - key: STARTUP_PROBE_DELAY_MS
        value: "5000"
      # Monitoring configuration
      - key: METRICS_PORT
        value: "9090"
      - key: ENABLE_REQUEST_LOGGING
        value: "true"
      - key: ENABLE_PERFORMANCE_TRACKING
        value: "true"
    
    alerts:
      - rule: CPU_UTILIZATION
        value: 85
      - rule: MEM_UTILIZATION  
        value: 85
      - rule: RESTART_COUNT
        value: 5

# Redis for caching
databases:
  - name: redis-cache
    engine: REDIS
    version: "7"
    size: basic
    num_nodes: 1

# Static assets
static_sites:
  - name: static-assets
    source_dir: /public
    github:
      repo: SpacePlushy/portfolio
      branch: build-fixes
      deploy_on_push: true
    
    routes:
      - path: /assets
      - path: /images
      - path: /fonts
    
    envs:
      - key: CDN_CACHE_CONTROL
        value: "public, max-age=31536000, immutable"

# Alerts configuration
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED