#
# Digital Ocean App Platform - OPTIMIZED CONFIGURATION
# Fixes for 504 errors and health check timeouts
#
name: portfolio-app
region: nyc1

# Global environment variables
envs:
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8080"
  # Sharp optimizations for small instances
  - key: SHARP_IGNORE_GLOBAL_LIBVIPS
    value: "1"
  - key: SHARP_CACHE_SIZE
    value: "50"
  - key: SHARP_CONCURRENCY
    value: "1"
  - key: SHARP_SIMD
    value: "false"  # Disable SIMD on small instances
  # Node.js memory optimization
  - key: NODE_OPTIONS
    value: "--max-old-space-size=400"  # Leave headroom for 0.5GB instance
  # Startup optimization
  - key: STARTUP_GRACE_PERIOD
    value: "30"  # Seconds to wait before full health checks
  - key: STARTUP_TIMEOUT
    value: "120000"  # 2 minutes max startup time

# Main application service
services:
  - name: portfolio
    github:
      repo: SpacePlushy/portfolio
      branch: build-fixes
      deploy_on_push: true
    
    # Build configuration
    build_command: npm ci --production=false && npm run build
    run_command: npm start
    
    # Use Dockerfile for optimized builds
    dockerfile_path: Dockerfile
    
    # Instance configuration
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs  # 0.5GB RAM, 1 vCPU
    
    # Port configuration
    http_port: 8080
    
    # Optimized health checks for fast startup
    health_check:
      # Use quick mode of unified health endpoint
      http_path: /api/health?quick=true
      initial_delay_seconds: 10   # Quick initial check
      period_seconds: 10          # Frequent checks
      timeout_seconds: 5          # Fast timeout
      success_threshold: 1        # Single success is enough
      failure_threshold: 3        # Allow some failures during startup
    
    # Service-specific environment variables
    envs:
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

# Static file serving (offload from main app)
static_sites:
  - name: portfolio-static
    github:
      repo: SpacePlushy/portfolio
      branch: build-fixes
      deploy_on_push: true
    
    source_dir: /public
    
    routes:
      - path: /assets
      - path: /images
      - path: /fonts
      - path: /favicon.ico
      - path: /robots.txt

# Alerts for monitoring
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE