# Prometheus configuration for image optimization monitoring
# Collects metrics from application, Redis, and system components

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Application metrics
  - job_name: 'astro-app'
    static_configs:
      - targets: ['app:4321']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Custom image optimization metrics
  - job_name: 'image-optimization'
    static_configs:
      - targets: ['app:4321']
    metrics_path: '/api/metrics/images'
    scrape_interval: 60s
    scrape_timeout: 30s

  # Performance monitoring
  - job_name: 'performance'
    static_configs:
      - targets: ['app:4321']
    metrics_path: '/api/metrics/performance'
    scrape_interval: 30s